services:
  - type: web
    name: event-management-app
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: event-db
          property: connectionString